#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#pylint: disable-msg=e0401
#pylint: disable-msg=c0413

'''
Script for change user password
'''

import sys
import Ice
Ice.loadSlice("Icegauntlet.ice")
import IceGauntlet


class Client(Ice.Application):

    '''
    Client class for change user password
    '''

    def run(self,argv):
        proxy = self.communicator().stringToProxy(argv[1])
        authentication = IceGauntlet.AuthenticationPrx.checkedCast(proxy)
        if not authentication:
            raise RuntimeError('Invalid proxy')

        token = argv[2]

        try:
            user = authentication.getOwner(token)
            print(user)
        except IceGauntlet.Unauthorized:
            print("Password not valid")



if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("usage: ./ChangePassword <proxy> <token>")
        sys.exit(1)
    sys.exit(Client().main(sys.argv))
