#!/usr/bin/bash

# Si existen los eliminamos
rm -r /tmp/db
rm -r /tmp/IceGauntletApp

mkdir -p /tmp/db/registry /tmp/db/node1/servers /tmp/db/node2/servers 
#icegridnode --Ice.Config=node1.config esto lo hace Tobias en su SO
#icegridnode --Ice.Config=node2.config

#run-client:
#	./Client.py --Ice.Config=locator.config "printer1 -t -e 1.1 @ PrinterServer$(SERVER).PrinterAdapter"

mkdir -p /tmp/IceGauntletApp
cp -r * /tmp/IceGauntletApp
icepatch2calc /tmp/IceGauntletApp
