#!/usr/bin/bash

# Si existen los eliminamos
rm -r /tmp/db 2>/dev/null
rm -r /tmp/IceGauntletApp 2>/dev/null

mkdir -p /tmp/db

# creamos la BD de rooms
touch /tmp/db/rooms.json & cp rooms.json /tmp/db/rooms.json

cp users.json /tmp/db/users.json 2>/dev/null

mkdir -p /tmp/db/registry /tmp/db/node1/servers /tmp/db/node2/servers

mkdir -p /tmp/IceGauntletApp
cp -r * /tmp/IceGauntletApp
/usr/bin/icepatch2calc /tmp/IceGauntletApp

#mkdir -p /tmp/db

#mkdir -p /tmp/db/registry /tmp/db/node1/servers /tmp/db/node2/servers
#icegridnode --Ice.Config=node1.config esto lo hace Tobias en su SO
#icegridnode --Ice.Config=node2.config

#run-client:
#	./Client.py --Ice.Config=locator.config "printer1 -t -e 1.1 @ PrinterServer$(SERVER).PrinterAdapter"

