#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#pylint: disable-msg=e0401
#pylint: disable-msg=c0413

'''
Script that allows an user to upload a map
'''

import sys
import time
import json
from pwn import log
import Ice
Ice.loadSlice("Icegauntlet.ice")
import IceGauntlet

class Client(Ice.Application):

    '''
    class that contains the code to upload a map to the server
    '''

    def run(self,argv):
        proxy = self.communicator().stringToProxy(argv[1])
        roomservice = IceGauntlet.RoomManagerPrx.checkedCast(proxy)
        if not roomservice:
            raise RuntimeError('Invalid proxy')

        token = argv[2]
        room_file = argv[3]
        progress_variable = log.progress("Trying to Push the Room...")
        time.sleep(1)
        try:
            file = open(room_file,'r')
            roomjson = json.loads(file.read())
            room_data = json.dumps(roomjson)
            roomservice.publish(token,room_data)
            progress_variable.status("Room sending...")
            time.sleep(1)
            progress_variable.success("Done")
        except IceGauntlet.Unauthorized:
            progress_variable.failure("Token not valid")
        except IceGauntlet.RoomAlreadyExists:
            progress_variable.failure("The room already exists")
        except IceGauntlet.WrongRoomFormat:
            progress_variable.failure("The roomData format is not valid")

if __name__ == "__main__":

    if len(sys.argv) != 4:
        print("usage: ./upload_map <proxy> <token> <roomdata>")
        sys.exit(1)
    sys.exit(Client().main(sys.argv))
