#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import Ice
Ice.loadSlice("Icegauntlet.ice")
import IceGauntlet
import os, hashlib, sys
import getpass
from pwn import *
import time,json

class Client(Ice.Application):

    def run(self,argv):
        proxy = self.communicator().stringToProxy(argv[1])
        roomManager = IceGauntlet.RoomManagerPrx.checkedCast(proxy)
        if not roomManager:
            raise RuntimeError('Invalid proxy')

        token = argv[2]
        roomName = argv[3]
        p = log.progress("Trying to Remove the Room...")
        time.sleep(1)
        try:
            roomManager.remove(token,roomName)
            p.status("Room removing...")
            time.sleep(1)
            p.success("Done")
        except IceGauntlet.Unauthorized:
            p.failure("Token not valid")
        except IceGauntlet.RoomNotExists:
            p.failure("The room not exists")

if __name__ == "__main__":

    if len(sys.argv) != 4:
        print("usage: ./ClientRemove <proxy> <token> <roomname>")
        sys.exit(1)
    sys.exit(Client().main(sys.argv))
